### ISSUE TITLE
Plugin is not installing

### ISSUE THREAD

**Issue by akup11** [nikosgram/gringotts-towny#7]
Gringotts, Towny and Vault plugins all work as expected, but gringotts_towny refuses to install. MC version is 1.19.4 and all plugins are at their most up-to-date versions.

This is the error coming up on dashboard when starting the server:
> [modernpluginloadingstrategy] could not load plugin 'gringotts-towny-2.12.4-snapshot (2).jar' in folder 'plugins' org.bukkit.plugin.invalidpluginexception: java.lang.noclassdeffounderror: org/gestern/gringotts/api/dependency/dependency at io.papermc.paper.plugin.provider.type.spigot.spigotpluginprovider.createinstance(spigotpluginprovider.java:127) ~[paper-1.19.4.jar:git-paper-514] at io.papermc.paper.plugin.provider.type.spigot.spigotpluginprovider.createinstance(spigotpluginprovider.java:35) ~[paper-1.19.4.jar:git-paper-514] at io.papermc.paper.plugin.entrypoint.strategy.modernpluginloadingstrategy.loadproviders(modernpluginloadingstrategy.java:150) ~[paper-1.19.4.jar:git-paper-514] at io.papermc.paper.plugin.storage.simpleproviderstorage.enter(simpleproviderstorage.java:35) ~[paper-1.19.4.jar:git-paper-514] at io.papermc.paper.plugin.entrypoint.launchentrypointhandler.enter(launchentrypointhandler.java:36) ~[paper-1.19.4.jar:git-paper-514] at org.bukkit.craftbukkit.v1_19_r3.craftserver.loadplugins(craftserver.java:423) ~[paper-1.19.4.jar:git-paper-514] at net.minecraft.server.dedicated.dedicatedserver.initserver(dedicatedserver.java:273) ~[paper-1.19.4.jar:git-paper-514] at net.minecraft.server.minecraftserver.runserver(minecraftserver.java:1104) ~[paper-1.19.4.jar:git-paper-514] at net.minecraft.server.minecraftserver.lambda$spin$0(minecraftserver.java:320) ~[paper-1.19.4.jar:git-paper-514] at java.lang.thread.run(thread.java:833) ~[?:?]

**Comment by nikosgram** [comment]
Duplicated #6 

It appears that Gringotts is absent. For Gringotts Towny to function, Gringotts is required as it holds all the essential functionalities. Gringotts Towny essentially provides Towny support.

Feel free to download it from Spigot at the following link:

https://www.spigotmc.org/resources/gringotts.42071/

❤️
